src/pet_shop/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/", to: "dogs#home", as: "root"
  get "/dogs", to: "dogs#index", as: "dogs"
  get "/dogs/new", to: "dogs#new", as: "new_dogs"
  post "/dogs", to: "dogs#create"
  get "/dogs/:id", to: "dogs#show", as: "dog"

  get "/dogs/:id/edit", to: "dogs#edit", as: "edit_dogs"
  put "dogs/:id", to: "dogs#update"
  patch "/dogs/:id", to: "dogs#update"
  delete  "dogs/:id", to: "dogs#destroy"
  get "/whoweare", to:"dogs#whoweare"
  get "/contactus", to:"dogs#contactus"
  get "aboutus", to: "dogs#aboutus"
end

src/pet_shop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/pet_shop/app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  validates :title, :description, :age, :name, :breed, presence: true
  has_one_attached :picture


end

src/pet_shop/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :dogs, dependent: :destroy
end

src/pet_shop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

src/pet_shop/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
before_action :authenticate_user!


def home

end 

def index
    
    @dogs = Dog.all
    
end

def new 
    
    @dog = Dog.new  

end 


def create
    @dog = current_user.dogs.create(dog_params)
    if 
    @dog.errors.any?
    render "new"
    else 
        redirect_to dogs_path
    end
end 


def show
    @dog = Dog.find(params[:id])
end 


def edit
    @dog = Dog.find_by_id(params[:id])
    if 
    @dog 
    render ("edit")
    else 
    redirect_to dogs_path
    end
end 

def update 
    @dog = Dog.find_by_id(params[:id])
    if 
    @dog
    @dog.update(dog_params)
    if 
    @dog.errors.any?
    render "edit"
    else 
        redirect_to dogs_path
 end 
    else 
    redirect_to dogs_path
end
end 


def destroy 
    @dog = Dog.find_by_id(params[:id])
    if 
    @dog
    @dog.destroy
    redirect_to dogs_path
    end
end 

def whoweare

end 

def contactus

end


def thankyou


end


def account


end



def aboutus 

end 

private 
def dog_params

    params.require(:dog).permit(:title, :description, :breed, :age, :picture, :name)

end 

end 

src/pet_shop/app/helpers/application_helper.rb
module ApplicationHelper
end

src/pet_shop/app/views/dogs/_form.html.erb
<%= render "header", dog: @dog %>

<% if dog.errors.any? %>”
    <ul> 
    <% dog.errors.full_messages.each do |error| %>
    <li> <%=error%></li> 
<%end%>    
    </ul>
    <%end%>    
<br>
    <br>

<%= form_with model: dog, local: true do |form| %>
    
    <center><%= form.label :"Listing title" %></center>
        <center><%= form.text_field :title, value: dog.title %></center>
        <br>  
    <center><%= form.label :"Name" %></center>
        <center><%= form.text_field :name, value: dog.name %></center>
        <br>
    <center><%= form.label :"Description" %></center>
    <center><%= form.text_area :description, value: dog.description, "cols" => 100, "rows" => 15 %></center>
        <br>
    <center><%= form.label :"Breed" %></center>
    <center><%= form.text_area :breed, value: dog.breed%></center>
    <br>
    <center><%= form.label :"Age" %></center>
    <center><%= form.text_area :age, value: dog.age %></center>
    <br>
    <center><%= form.label :"State" %></center>
    <center><%= form.text_area :state, value: dog.state %></center>
    <br>
    <br>
    <center>Potty trained?
<%= check_box_tag(:dog) %>
<%= label_tag(:dog, "Yes") %>
<%= check_box_tag(:dog) %>
<%= label_tag(:dog, "No") %>
<%= form.label :"Likes Dogs?" %>
<%= check_box_tag(:yes_potty_trained) %>
<%= label_tag(:pet_dog, "yes") %>
<%= check_box_tag(:no_potty_trained) %>
<%= label_tag(:pet_cat, "no") %>
<%= form.label :"Likes Children?" %>
<%= check_box_tag(:yes_potty_trained) %>
<%= label_tag(:pet_dog, "yes") %>
<%= check_box_tag(:no_potty_trained) %>
<%= label_tag(:pet_cat, "no") %><center>
<br>
<center><%= form.label :picture %>
<%= form.file_field :picture, accept: "image/png,image/gif,image/jpeg,image/jpg" %></center>
<br>
<%= form.submit %>
<% end %>

src/pet_shop/app/views/dogs/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
    
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
    </a>


<div id="navbarBasicExample" class="navbar-menu">
  <div class="navbar-start">
    <a class="navbar-item">
    <%= link_to 'Pet Match', root_path %>
    </a>

    <a class="navbar-item">
        <%= link_to 'Home', root_path %>
    </a>

    <a class="navbar-item">
        <%= link_to 'Who We Are', "/aboutus" %>
    </a>

    <a class="navbar-item">
        <%= link_to 'Adopt', "/dogs" %>
    </a>

    <a class="navbar-item">
        <%= link_to 'Contact Us', "/contactus" %>
    </a>
    </div>
</div>
</nav>

src/pet_shop/app/views/dogs/aboutus.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="all.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <style>

#navbarBasicExample{
    font-size: 20px;
    background-color; 
    }
      
a {
    color:black;
    text-decoration: none;
}

.title {
    text-align: center;
}
    
    </style>
</head>


<%= render "header", dog: @dog %>

<section class="hero is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
            Adopt your new best friend!
            </h1>
        </div>
    </div>
</section>



<br>
<p class="title is-1 is-spaced mt-5 ">Who We Are </p>
<p class="subtitle is-3">Dog match is a non-profit group that matches 
dogs in shelters across NSW to their new forever homes! We believe every 
animal deserves a loving home and it is our aim to match pets to the lifestyle of 
potentional owners. This ensures a happy and long lasting relationship for the pups 
and their new best friend! <br> <br>All dogs listed have undergone a comprehensive 
vet check and are microchipped, desexed and treated for parasites. Rest assured your 
new best friend will arrive happy and healthy. <br><br>We also pride ourselves in 
featuring a wide range of breeds, ages, and temperament so you have a wider variety to 
choose from and also so that each dog is given a chance at a new loving home. If you find
 a dog that is right for you, please contact the listed shelter to make arrangements to 
 meet your potential new pet. Make a difference to a pet's life and 
Adopt. 


<br><br><br><br>
 <center> <%= image_tag "volunteer-PA.jpg",:style => 'height:400px;width:auto;' %>  

 <footer class="footer">
 <div class="content has-text-centered">
 <p>
 <strong>&copy; 2020 Pet Shop</strong> 
 </p>
 </div>
</footer>

src/pet_shop/app/views/dogs/contactus.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="all.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <style>

#navbarBasicExample{
    font-size: 20px;
    background-color; 
    }
      
a {
    color:black;
    text-decoration: none;
}

.title {
    text-align: center;
}
    
    </style>
</head>


<%= render "header", dog: @dog %>

<section class="hero is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
            Adopt your new best friend!
            </h1>
        </div>
    </div>
</section>


<section class="hero is-fullheight">
	<div class="hero-body">
	<div class="container has-text-centered">
	<div class="columns is-7 is-variable ">
	<div class="column is-two-thirds has-text-left">
		<p class="is-size-1">Contact Us</p>
		<p class="is-size-4">For questions or concerns, please email: dogmatch@inquries.com.au</p>
		<div class="social-media">
			<a href="https://facebook.com" target="_blank" class="button is-light is-large"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
				<a href="https://instagram.com" target="_blank" class="button is-light is-large"><i class="fa fa-instagram" aria-hidden="true"></i></a>
				<a href="https://twitter.com" target="_blank" class="button is-light is-large"><i class="fa fa-twitter" aria-hidden="true"></i></a>
		</div>
	</div>
				

src/pet_shop/app/views/dogs/edit.html.erb
<%= render "form", dog: @dog %>
<%= render "header", dog: @dog %>

src/pet_shop/app/views/dogs/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="all.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <style>

#navbarBasicExample{
    font-size: 20px;
    background-color; 
    }
      
a {
    color:black;
    text-decoration: none;
}

.title {
    text-align: center;
}
    
    </style>
</head>


<%= render "header", dog: @dog %>

<section class="hero is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
            Adopt your new best friend!
            </h1>
        </div>
    </div>
</section>


<h1 class="title is-1 mt-5 ">
  <center>Here are our top featured dogs in NSW </center>
</h1>


<div class="container">
    <div id="flow">
        <span class="flow-1"></span>
        <span class="flow-2"></span>
        <span class="flow-3"></span>
    </div>
</div>
        
 <div class="row columns">
    <div class="column is-one-third">
        <div class="card large">
            <div class="card-image">
                <figure class="image">
                    <%= image_tag "scrappy.jpg",:style => 'height:400px;width:auto;' %>
                </figure>
            </div>
                    
<div class="card-content">
    <div class="media">
        <div class="media-left">
            <figure class="image is-96x96">   
            </figure>
        </div>
                            
        
<div class="media-content">
    <p class="title is-4 no-padding">Murphy Loves to play fetch!</p>
        <%= link_to "Find out more", dog_path(2)%>
</div>
</div>
                        
<div class="content">
</div>
</div>
</div>
</div>

<div class="column is-one-third">
     <div class="card large">
        <div class="card-image">
            <figure class="image">
                <%= image_tag "Chico.jpg",:style => 'height:400px;width:auto;'  %>
            </figure>
        </div>
                
<div class="card-content">
    <div class="media">
        <div class="media-left">
            <figure class="image is-96x96"> </figure>
        </div>

<div class="media-content">
    <p class="title is-4 no-padding">Energetic and loving</p>
        <%= link_to "Find out more", dog_path(2)%>
    </div>
</div>
                
<div class="content">
</div>
</div>
</div>
</div>
                    
<div class="column is-one-third">
    <div class="card large">
        <div class="card-image">
            <figure class="image">
                <%= image_tag "panda.jpg",:style => 'height:400px;width:auto;' %>
            </figure>
        </div>
                                                                
<div class="card-content">
    <div class="media">
        <div class="media-left">
            <figure class="image is-96x96">
            </figure>
        </div>

<div class="media-content">
    <p class="title is-4 no-padding">Loves children and dogs!</p>
    <%= link_to "Find out more", dog_path(2)%>
    <div class="column is-6 is-offset-1">
    <h1 class="title is-2"></h1>                
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<center>  
<button class="button is-light">  
<%= link_to 'View More', "/dogs" %>
</button>  
</center> 
                                         

                                                         
                                                          
<br> <br> <br>
<p class="title is-1 is-spaced mt-5 ">Why adopt?</p>
<p class="subtitle is-3">
    Thousands of dogs are surrendered to animal shelters across NSW every year. 
    Adopting a dog from a shelter is the perfect way to give a dog a second chance at finding happiness in a new 
    loving home. Most importantly, adoption saves lives.
    <br> <br>
    Every time an animal is adopted to a furever home, a space is opened in the shelter and foster care network
    for another dog in need. Adoptions also effectively reduces overcrowded shelters which unfortuntely can lead to euthanizations. 
    <br> <br> Make a difference to a pet's life and Adopt. 
    <br> <br> <br>
    <p class="title is-1 is-spaced mt-5 ">Who We Are</p>     
     <p class="subtitle is-3">
    <br> 
    Dog match is a non-profit group that matches dogs in shelters
    across Australia to their new forever homes! We believe every
    animal deserves a loving home and it is our aim to match pets to 
    the lifestyle of potentional owners. This ensures a happy and long 
    lasting relationship for the pups and their new best friend! All dogs 
    listed have undergone a  comprehensive vet check and are microchipped, 
    desexed and treated for parasites. Rest assured your new best friend will 
    arrive happy and healthy. <br><br>We also pride ourselves in featuring a 
    wide range of breeds, ages, and temperament so you have a wider variety to choose 
    from and also so that each dog is given a chance at a new loving home. If you 
    find a dog that is right for you, please contact the listed shelter to make 
    arrangements to meet your potential new pet.  
   <center> <%= image_tag "volunteer2.jpg" %>  </center>
                                                

<footer class="footer">
    <div class="content has-text-centered">
    <p>
    <strong>&copy; 2020 Pet Shop</strong> 
    </p>
    </div>
</footer>

src/pet_shop/app/views/dogs/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="all.css">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <style>

#navbarBasicExample{
    font-size: 20px;
    background-color; 
    }
      
a {
    color:black;
    text-decoration: none;
}

.title {
    text-align: center;
}

.row-columns {
    background-image: url("assets/chico.jpg");
    height: 40vh; /*take up half the browser size, the legnth */ 
    background-size: cover; /*fills the area*/
  }

    </style>
</head>


<%= render "header", dog: @dog %>

<section class="hero is-dark">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
            Adopt your new best friend!
            </h1>
        </div>
    </div>
</section>



<h1 class="title is-1 mt-5 ">
  <center>Pet Match Profiles </center>


  <%= link_to "Create a listing", new_dogs_path %><br>
<br>
<br>
<div class="container">
    <div id="flow">
        <span class="flow-1"></span>
        <span class="flow-2"></span>
        <span class="flow-3"></span>
    </div>
    <div class="row columns">
        <div class="column is-one-third">
        <% for dog in @dogs %> 
            <div class="card large">
                <div class="card-image">
                    <figure class="image">
                        <%= image_tag dog.picture if dog.picture.attached?%>
                    </figure>
                </div>
                <div class="card-content ">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-96x96">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-4 no-padding"> <%= link_to dog.title, dog_path(dog.id)%> </p>
                            <p class="subtitle is-6"> <%= dog.breed %> </p>
                            
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>
                            

src/pet_shop/app/views/dogs/new.html.erb
<%= render "form", dog: @dog %>
<%= render "header", dog: @dog %>

src/pet_shop/app/views/dogs/show.html.erb
<%= render "header", dog: @dog %>


                        
<% if @dog.picture.attached? %>
<%= image_tag @dog.picture, style: "width: 350px" %>
<% end %>

<div class="column is-6 is-offset-1">
   <h1 class="title is-2">
   <h1><%= @dog.title %></h1>
   </h1>
   <br>
                        Breed: <%= @dog.breed %>
                        <br>
                        Name: <%= @dog.name %>
                        <br>
                        <br>
                        Description: <%= @dog.description %>
                        <br>
                        <br>
                        Age: <%= @dog.age %>
                        <br>
                        <br>
                        Location: <%= @dog.state  %>
                        <br>
                        <br>
                        Potty Trained?<%= @dog.potty_trained %>
                        <br>
                        Likes children?<%= @dog.likes_children %>
                        <br>
                        Likes Dogs?<%= @dog.likes_dogs %>
                        <br>
                        <% if current_user.id == @dog.user.id %>
                        <%= link_to  "edit", edit_dogs_path(@dog.id) %>
                        <%= form_with model: @dog, local: true, method: "delete" do |form| %>
                     <%= submit_tag "delete" %>
                        <% end %>
                        <% end %>
                        
                    </div>
            
           

src/pet_shop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetShop  </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
	  <link rel="stylesheet" href="https://unpkg.com/bulma@0.8.0/css/bulma.min.css" />
  	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
  </head>

  <body>
  <% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to "Login/SignUp", new_user_session_path %>
  <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

src/pet_shop/app/views/pages/home.html.erb
<h1> Dog Listings </h1>
<h2> Your dream dog is waiting </h2>
<h3> Take a peek below </h3>